### ISSUE TITLE
Enable online demo for all time series examples.

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-lib-viz-highcharts-js#16]
Now that we have online demos for some (most?) of the time series examples, it is confusing when an example is missing.  I suggest that all examples have the online demo feature so that readers are not confused.  And, it should be an expectation for staff to be consistent when adding a new demo.

It is also a bit confusing that clicking on the thumbnail brings up a larger image.  I think I would rather click on the thumbnail to navigate to the example, and then see the larger image there with access to code and the live demo.  For example, the main OWF website takes this approach to navigate to visualizations, stories, etc.

**Comment by masforce** [comment]
Enabled live demos for all examples and simplified the README.md file with larger images and better links
